azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=raghustorage514;AccountKey=teskKbAzx0EwN49HdXkNLopqeGssdXvH/8+WBFdfiMc0GvRUPaJOGwYBSopS0DILN7DiZFY3lnuj+AStRbJNHA==;EndpointSuffix=core.windows.net
    container-name: media-container
    sas: sp=r&st=2026-01-31T08:52:54Z&se=2028-09-01T17:07:54Z&sv=2024-11-04&sr=c&sig=TuHB3lGGzcCygu6JMddE74%2Bd93J7jFliRxemLz5SMaw%3D
  function:
    url: https://function-app-dev-g5dqe8eqd7apekgh.centralindia-01.azurewebsites.net/api/processOrder
    key: function-app-dev